#!/bin/bash

which fossPrj  1> /dev/null
if [ $? -ne 0 ]; then
	echo "fossPrj not installed"
	exit 1
fi

while true; 
do
	read -p "Enter channel number to change to: " pattern
	case ${pattern} in
		*[!1-2]* ) 
			printf " Please enter a number between 0 and 2 \n 1 - Unencrypted \n 2 - Encrypted \n ctrl + c to exit \n"
			;;
		*[1-2]* ) 
			echo $pattern | fossPrj 1> /tmp/hello
			val=`cat /tmp/hello`
			if [ $val -gt 199 -a $val -lt 300 ]
			then
				printf "Changed to channel : $pattern \n"
			else
				printf "Couldn\'t contact server. Please try again later\n"
			fi
			;;
	esac
done
