#!/bin/sh

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog


end () {
	exit
}

while true
do
	cmd=($DIALOG --keep-tite --menu "Select channel :" 11 30 16)

	options=(1 "Unencrypted"
		 2 "Encrypted")

	choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
	for choice in $choices
	do
		case $choice in
			[1-2])
				mode="Encrypted"
				if [ $choice -eq 1 ]
				then
					mode="Encryption disabled"
				fi
				echo $choice | fossPrj 1> /tmp/hello
				val=`cat /tmp/hello`
				if [ $val -gt 199 -a $val -lt 300 ]
				then
					display="Changed to channel : $mode. Would you like to continue? \n"
				else
					display="Couldn\'t contact server. Please try again later\n"
				fi
				    $DIALOG --yesno "$display" 10 25 || end		
			;;
		    esac
		done
	done
